### ISSUE TITLE
Create AUR package

### ISSUE THREAD

**Issue by Holzhaus** [Apokalypzx/kodi-c1-fb#1]
I would be great if you created an AUR package to make it easier to install & update kodi. 

``` bash
mksrcinfo
git add .SRCINFO
git commit --amend
git push -f origin master
git remote add aur  ssh://aur@aur.archlinux.org/kodi-c1-fb.git
git push aur master
```

See https://wiki.archlinux.org/index.php/Arch_User_Repository#Creating_a_new_package for details.

**Comment by Apokalypzx** [comment]
Done.
https://aur.archlinux.org/packages/kodi-c1-fb/
